name: Criar APK

on:
  push:
    branches: [principal, main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checar reposit√≥rio
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/gradle-build-action@v3

      - name: Construir projeto Android
        working-directory: android
        run: |
          chmod +x gradlew || true
          gradle wrapper
          ./gradlew assembleDebug --stacktrace

      - name: Publicar APK
        uses: actions/upload-artifact@v4
        with:
          name: EncontroNaEsquina-App
          path: android/app/build/outputs/apk/debug/app-debug.apk
